name: Docker Image CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: get_version
      id: get_version
      run: echo ::set-env name=RELEASE_VERSION::$(echo $(grep "VERSION=" Dockerfile|cut -d"=" -f2))
    - name: Build and publish images
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: hyr326/apioak
        tags: "v${{ env.RELEASE_VERSION }},latest"
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile